'''

PIPELINE 2

Project manager for Maya

Ahutor: Lior Ben Horin
All rights reserved (c) 2017

pipeline.nnl.tv
liorbenhorin@gmail.com

---------------------------------------------------------------------------------------------

install:

Place the pipeline folder in your maya scripts folder and run this code (in python):

import pipeline
pipeline.start()

---------------------------------------------------------------------------------------------

You are using pipeline on you own risk.
Things can always go wrong, and under no circumstances the author
would be responsible for any damages caused from the use of this software.
When using this beta program you hereby agree to allow this program to collect
and send usage data to the author.

---------------------------------------------------------------------------------------------

The coded instructions, statements, computer programs, and/or related
material (collectively the "Data") in these files are subject to the terms
and conditions defined by
Creative Commons Attribution-NonCommercial-NoDerivs 4.0 Unported License:
   http://creativecommons.org/licenses/by-nc-nd/4.0/
   http://creativecommons.org/licenses/by-nc-nd/4.0/legalcode
   http://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.txt

---------------------------------------------------------------------------------------------

'''

import os
import socket

import pipeline.libs.serializer as serializer


def verifyLockFile(path):
    if os.path.isfile(path):

        j = serializer.Metadata_file(path=path)
        info = j.data_file.read()
        if info:
            host = info["host"]
            if host == socket.gethostname():
                ''' the file was generated by this machine '''
                return True
            else:
                ''' the file was generated on a different machine '''
                print "{} was not genereted by {}".format(os.path.basename(path), socket.gethostname())
                return False
    ''' No lock file... '''
    return True